### ISSUE TITLE
Renamed GApple bug

### ISSUE THREAD

**Issue by baticag** [gvlfm78/BukkitOldCombatMechanics#10]
Players on my server started duping golden apples and enchanted golden apples.

It only happens with gapples with custom display name without lore, and it works like shown in the video: http://download.serb-craft.com/applebug.mp4

Can you please fix this?

**Comment by Rayzr522** [comment]
Hmmm...
That is beyond weird.

Time to go sift through our code :P

**Comment by Rayzr522** [comment]
Hmmm, I'm not able to duplicate it.

**Comment by Rayzr522** [comment]
Yeah, I followed your exact steps.

Do you have any custom food plugins or plugins that do anything with the offhand slot? I find it very odd that the duped gapple is being put into your offhand slot.

Also our code does nothing with named items. I see no reason why it would mess it up to be renamed.

**Comment by baticag** [comment]
I am 100% sure that it is coming from OCM because when I remove it dupe isn't happening.

I don't have any custom food plugins or anything related to gapples. This is my OCM config: http://pastebin.com/EC7Pjv6J

**Comment by Rayzr522** [comment]
I actually WAS able to reproduce the bug after sending that message. I didn't say that immediately though because my computer failed (for some reason all my memory was suddenly used??).

Aha! After further testing it's the `enchanted-golden-apple-crafting` option. Now that I have a starting point I'll go and check it out.

**Comment by Rayzr522** [comment]
This is extremely confusing. The `onItemConsume` doesn't even *reference* `enchanted-golden-apple-crafting`, yet the bug is happening *in* `onItemConsume`.

I'm going to talk to the other guy that works on this plugin with me and see if I can't get some insight into this. A fresh set of eyes might help.

**Comment by baticag** [comment]
Okay, thank you, if you need any more info or testing you can contact me

**Comment by gvlfm78** [comment]
@baticag I believe I have managed to fix this, could you try out [this test version](https://jenkins-bukkitocm.rhcloud.com/job/OldCombatMechanics/71/artifact/target/OldCombatMechanics.jar) and tell us if you still get the bug?

**Comment by baticag** [comment]
Yes it's fixed in that version thanks!

**Comment by gvlfm78** [comment]
I will be releasing this fix as version 1.0.2
