### ISSUE TITLE
Some cool suggestions !

### ISSUE THREAD

**Issue by FrenzyCake** [gvlfm78/BukkitOldCombatMechanics#107]
Hello there!
Here I will post all of my cool suggestions I think will drastically change PvP experience to better, maybe even better than it was in 1.7 version.
**Suggestion 1)** Can you make a mod for forge that will add back block-hit feature in 1.9+ versions. But that mod should be compatible with this plugin, if the server doesn't have this plugin it can't be used.

**Suggestion 2)** Disable all entity collisions feature.

**Suggestion 3)** Change 1.9+ sounds back to 1.7/1.8 sounds, they were much smoother and overall better.

**Suggestion 4)** Pre-1.9/1.7/1.8 Hitbox. I know there's already a suggestion about this, but I'll write it again, because it's one of the best suggestions I've seen so far.

**Suggestion 5)** Remove fishing rod pulling and just leave fishing rod knockback, fishing rod pulling is a new feature in 1.9+ version which a lot of people don't like, and there's currently no plugin on spigot which entirely disables it, so I think that would be pretty cool to see in this plugin features.

**Suggestion 6)** SmashHit features for better Hit Detection (Async Hit Detection), you can read all its info right here: https://github.com/Speentie8081/SmashHit

**Comment by gvlfm78** [comment]
1. OCM is a bukkit plugin, not a mod. If you find a way to implement this feature with a plugin open an enhancement ticket for it
2. Please create a new enhancement ticket for this specifying the details
3. There is already a ticket for this. I have not looked into it much yet so it would be helpful if someone specified which sounds changed to what. 
4. Already a suggestion. You may want to add some details to the already existing ticket
5. Create a new enhancement ticket for this, with details about what changed in what version and already existing plugins that do this or similar
6. There is already a ticket for this too. You may want to express your support for the feature and also post the plugin link there.

The reason for having separate tickets for various issues and enhancements is so that when I have time to work on OCM I can work on one specific thing and close the ticket when done, other than the discussion being contained.
