### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by zBoringDrop** [gvlfm78/BukkitOldCombatMechanics#130]
Hi, I would recommend adding a HitDelay option, example:
HitDelay: 1 #In seconds

Or a similar option that work similar to NoHitDelay plugin, but in this plugin and optimized for 1.9 to 1.12 :)
Can you add this in future?
(i'm italian)

**Comment by gvlfm78** [comment]
What is the purpose of the hit delay? Is it like issue #19?

**Comment by gvlfm78** [comment]
That doesn't mean anything, it simply isn't at the top of the list of priorities. For example, old potion effects affect combat more than hit delay and so that's what I'm working on now.

If you have anything you want to add regarding this hit delay, including your interest in its development, do so on issue #19
