### ISSUE TITLE
Shield blocking bug (+- armor)

### ISSUE THREAD

**Issue by baticag** [gvlfm78/BukkitOldCombatMechanics#145]
We did a test on the server with default config and Shield blocking module enabled and we found one critical bug:

No armor, no shield: -7hp
Armor, no shield: -2hp

No armor + shield: -4hp
Armor + shield: -4hp

So there is no change of damage when he has a shield with or without armor, as like having armor doesn't change anything.

Can you please fix that?

**Comment by gvlfm78** [comment]
What version of the plugin and Bukkit/Spigot do you have?

**Comment by baticag** [comment]
OldCombatMechanics by gvlfm78 and Rayzr522 version 1.6.3

[23:37:37 INFO]: This server is running Paper version git-Paper-1282 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[23:37:37 INFO]: Checking version, please wait...
[23:37:37 INFO]: You are running the latest version

**Comment by baticag** [comment]
Any news about this problem?

**Comment by gvlfm78** [comment]
Hmm so I have done some testing, and it seems that the armour DamageModifier when the plugin changes the blocking is set to 0 because the damage was going to be blocked entirely by the shield (before the plugin comes along). This means that MC is not calculating what the armour damage reduction would be and just blocks all the damage if you have the shield up. This is bad because unless I find a workaround, it means that the only way to solve this problem is for the plugin to manually calculate what the damage reduction due to the armour would be, taking into account armour strength, toughness, enchantments, and weapon damage and enchantments.

**Comment by baticag** [comment]
That is too much work and don't see why should you need to do that.

Do you think that this is something we need to report to Spigot to fix?

**Comment by gvlfm78** [comment]
Well you see, this is not really a bug, because if the DamageModifier for armour _were_ set, it would modify the total damage (that's its job) while the damage needs to simply be reduced to 0. Maybe there is a way to make the server think of it as a normal damage event (without shield) and then apply the damage reduction later, like calling the relevant event manually whilst cancelling the current one.

**Comment by baticag** [comment]
Will using the EntityDamageEvent instead of the current one help?

**Comment by gvlfm78** [comment]
@baticag I don't know if this will make a difference, but I have recently rewritten the entire damage re-calculation logic and I would like for you to check if this issue is still present in the [newest test build](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/lastSuccessfulBuild/). If it is, it may now be an easy fix due to the code changes.
