### ISSUE TITLE
Compatibility with CombatLog

### ISSUE THREAD

**Issue by Adrawyn** [gvlfm78/BukkitOldCombatMechanics#156]
Hello, can you make it compatible with the combatlog plugins https://dev.bukkit.org/projects/combatlog

I really need that, thank you.

Sincerely.

**Comment by Rayzr522** [comment]
How is it not compatible?

**Comment by Adrawyn** [comment]
When attack nothing appear.

I think Combatlog, listen DamageEvent and OldCombatMechanic cancel this event.

**Comment by Adrawyn** [comment]
I'm trying something i tell you if it good

**Comment by Rayzr522** [comment]
This isn't a problem with OldCombatMechanics, I just tested with OCM and CombatLog installed and CombatLog worked perfectly fine. Most likely it was a conflict with either another plugin or a problem with your permissions. Unless you can find some evidence that it is a problem caused by OldCombatMechanics, I'm going to leave this thread closed. And if you *do* have evidence that it is caused by OCM, then I'll need your config file for OCM for local testing purposes.
