### ISSUE TITLE
[Enhancement] Sounds pretty dumb but add 1.8 pvp to 1.8. LOL Read comment.

### ISSUE THREAD

**Issue by LethalSh0tt** [gvlfm78/BukkitOldCombatMechanics#158]
So what happened was I use Viaversion,ViaBackwards, and Via Rewind on my server. My server is using the latest version and I wanted 1.7-1.12 players to join. The thing is, the developer added 1.9 pvp to 1.8 pvp to be fair with the newer versions. I asked him to have an option, but he said its never going to be added. So, I had this plugin installed before I got the "Via's" and it seems this plugin supports 1.9-1.12 pvp because they have the delay bar. Since they added it to 1.8 and ProtocolSupport is outdated, Could you add 1.8 pvp to 1.8. Hope you understand what im saying. Thanks. Ill send you a link on how the 1.8 delay bar looks like on a 1.8 client.

https://ibb.co/j5tAjG

**Comment by Rayzr522** [comment]
**My opinion:**

> Don't bother trying to support such a wide range of players.

It's people like you who insist on supporting clients that are several years out of date that make the lives of developers like me frustrating, since we have to provide support for old server versions. Just run your server on 1.12.2 with OCM for 1.8 PVP. The number of people who you would lose would be close to none, if not none at all. Almost nobody uses the old clients anymore, and if they're the kind of player that was going to stay on your server anyways, they would be willing to take the 60 seconds to switch their version to 1.12.2. The kinds of people who are unwilling to do such a simple task so that they can play on your server are not the kinds of people who would remain active members or even members at all on your server. 

*However.*

On a more technical note, I doubt there would be any plausible way to work around whatever plugin is implementing the 1.9+ PVP. And even if there was, I feel like it's the responsibility of the developer of that plugin to add this option, not us. Again, I'm not even sure if we could, since it's plugin-implemented. 

But of course, this decision is up to @gvlfm78, just thought I'd put in my 2 cents first.

**Comment by gvlfm78** [comment]
What does adding 1.8 pvp to 1.8 even mean lol

**Comment by Rayzr522** [comment]
He’s running a server on 1.8, but he has plugins that allow both future (1.9+) and older (1.7) clients to connect. One of those plugins is adding 1.9+ PVP for all clients, old and new. He wanted us to essentially disable that part of the plugin since the developer of said plugin refuses to add an option to disable it himself.

**Comment by LethalSh0tt** [comment]
@Rayzr522 I have the latest version as I said I have it when I opened this enhancement. I'm going to try to explain.
So, I have a 1.12.2 server with protocolsupport which allows clients from 1.4-1.12 to join. Everything works fine. OCM works fine. I see via version which is better than protocolsupport but I need 2 other plugins to allow 1.7-1.12 clients to play. Now, when I put it inside my server, I see that 1.8 has a delay bar. I was confused so I went onto the forums of ViaBackwards and what they said is to ask someone else to fix this because they will not take out the 1.8 delay bar since other people would probably want the delay bar for all versions instead of none for all versions. I wanted it for all versions so my "Enchancement" was meaning to ask you if you could remove the cool down for 1.8 pvp. Hope I got it through.

**Comment by Rayzr522** [comment]
I understand that most people would want it, but not all, which is why they should add an option in the config file to disable it. It’s not our job to fix someone else’s plugin.

**Comment by LethalSh0tt** [comment]
@rayzr522 Thats what ive told the dev but he wasn't listening. I'll try asking again.

**Comment by LethalSh0tt** [comment]
He's making a true/false in the config. I don't need 1.8 pvp for 1.8 clients anymore lmao.
