### ISSUE TITLE
[Suggestion] Option to disable shield with specific items

### ISSUE THREAD

**Issue by SeDark** [gvlfm78/BukkitOldCombatMechanics#174]
I am currently using kitbattle advanced, this uses mushroom soup to recover life, the thing is that this soup is drunk instantly, and if you quickly change your sword for a soup, you can not drink it until the shield disappears, so I would like it to work as with the potions (that the shield did not move to protect)

**Comment by gvlfm78** [comment]
You can try adding the soup to the _noBlockingItems: []_ list under the __sword-blocking__ header in the config.yml.

**Comment by SeDark** [comment]
https://gyazo.com/1861252141dad8f92e26ed1875a0d2ce

With this gif maybe you understand better what I mean

https://i.gyazo.com/25a22938d4a1dec400c02102cf975d4b.png

**Comment by Rayzr522** [comment]
In theory, one way to handle this would be to automatically cancel/remove the shield when you switched hotbar slots. Perhaps this should be moved to the todo list.

**Comment by Rayzr522** [comment]
Possibly patched in 928b7ab9dff6b7378c376f5b6442fe9caa96367b, but I have yet to test the build. Since I am quite busy, I will most likely not have time to test this any time soon. However, if you would like to test it, here is a compiled JAR with the patch: 

[OldCombatMechanics-hotbar-patch-beta.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/1882567/OldCombatMechanics-hotbar-patch-beta.zip)
(GitHub required that the file be zipped first, but it just contains a JAR file)

Please let me know how it works out for you!

P.S. don't forget to remove the current OldCombatMechanics JAR file temporarily while testing the patched version :)

**Comment by SeDark** [comment]
Now it works correctly, thank you very much.
