### ISSUE TITLE
CombatTag + OCM: Invisible and permanently armor

### ISSUE THREAD

**Issue by CryinDaily** [gvlfm78/BukkitOldCombatMechanics#176]
There is a problem between these two plugins that cause them to have any armor in an invisible and permanently. I recorded a video about how it works: https://youtu.be/ug16RhvQIPo

Spigot version: 1.9.4-R0.1-SNAPSHOT-latest
OCM version: 1.6.5
My config (1.9.4): https://pastebin.com/raw/QQh4ba99
1.12.2 Config: https://pastebin.com/raw/74eAsAYS (Watch the video first)

Plugins list: CombatLogX, OldCombatMechanics, PlugMan, ProtocolLib, Vault, ViaVersions.

In the case of the CT plugin, I use two. One created by the owner of my server and another created by a developer of Spigot (CombatLogX).

**Comment by Rayzr522** [comment]
Wow, I hate to have taken so long to reply to this. Sadly I am quite busy.

Based on the functionality of the old armor module, I see no way that it is physically possible that OCM is the cause of this. Most likely it is a bug in Spigot itself, since it worked after you updated to 1.12.2. OCM applies no special armor value to the player itself, only the items, so upon the loss of the items the armor should be removed. 

Again, I apologize for the late reply. Regrettably, I don't think there's anything we can do about this. It sounds like a bug in Spigot itself, since OCM never interacts directly with any kind of armor value on the player (only on the items).

My best guess is that there is some kind of race condition or incorrect order of logic in 1.9.4 Spigot that was causing the effects of the change in the item attributes to apply *after* the items were removed, since we do reset the items' attributes to default when you log out. But again, there is simply no way to fix this, as it is a bug in Spigot itself.
