### ISSUE TITLE
Per-user combat mode does not persist after death

### ISSUE THREAD

**Issue by TimHarrio** [gvlfm78/BukkitOldCombatMechanics#181]
The ocm toggle are disabled after death :/

**Comment by Rayzr522** [comment]
You mean the effect of `/ocm toggle` does not apply when the player respawns?

**Comment by TimHarrio** [comment]
yes ^^

**Comment by Rayzr522** [comment]
Just wondering, on your server does the player respawn in a different world from the one they died in?

**Comment by TimHarrio** [comment]
yes

**Comment by Rayzr522** [comment]
The inherit issue with `/ocm toggle` is that it does not have any way to keep track of which users have their combat mode toggled, which means the only way to solve this and properly implement #179 is to have some sort of data system which persistently keeps track of the combat mode of each user. I'll have to talk this over with @gvlfm78.

**Comment by gvlfm78** [comment]
@Rayzr522 Then the plugin would have to check if the player attacking an entity is on 1.8 or 1.9 mode and don't change the damage if on 1.8 mode. This _could_ now be possible since I recently unified the damage listeners into a custom event, however there would still be many modules that would have to support this.

**Comment by Rayzr522** [comment]
@gvlfm78 so currently `/ocm toggle` only toggles the attack speed?

**Comment by gvlfm78** [comment]
Yes, as whoever initially requested the feature only meant it to toggle the attack speed.

**Comment by gvlfm78** [comment]
Merged into #179
