### ISSUE TITLE
write@481395245

### ISSUE THREAD

**Issue by leoncp9** [gvlfm78/BukkitOldCombatMechanics#200]
## Info

- Server version: paper spigot 1.12.2
- OldCombatMechanics version: Compilazione #45 (18-lug-2018 15.21.06) 
- Server log file: 
- OldCombatMechanics config file: 

## Problem Description
> 
23.07 01:49:58 [Server] WARN [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@481395245)

**Comment by I-Al-Istannen** [comment]
Are you *sure* you are on the newest build (>= 42)? Because that is a known issue that was fixed in build 42 [here](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/42/). So any newer version than this should do.

If you know how, giving me the sha256 or md5 sum of the jar file (or uploading it somewhere, so I can have look) would allow me to verify that you are indeed on a newer version.

**Comment by Rayzr522** [comment]
Were you able to resolve your issue by upgrading to a newer dev version?

**Comment by gvlfm78** [comment]
Should I be releasing the latest dev version as a new bugfix patch to avoid this sort of ticket coming up again?

**Comment by I-Al-Istannen** [comment]
It came up a few (idk, maybe 3? 4?) times already, so that sounds good.

The other changes seem to be Spartan support (you can diff it, but it shouldn't break things — that sentence is dangerous though ;) and a bug fix from Rayzr.

So that'd be a :+1: from me.
