### ISSUE TITLE
1.13 compatibility.

### ISSUE THREAD

**Issue by TheIntelloBox** [gvlfm78/BukkitOldCombatMechanics#204]
Hey,

Is OldCombatMechanics compatible with 1.13 ? 🗡 

Thanks !

**Comment by detobel36** [comment]
Try :smile:          
If you have some bugs, report it here...

**Comment by Rayzr522** [comment]
I tried OCM in a 1.13 server and it seemed at least at first glance to be fully functional. I'm sure there will be some minor bugs we can fix later on, but otherwise it appears to be fully functional. 

Plugins, unlike mods, utilize an API that is designed to have as few if any breaking changes per Minecraft update. This means that plugins often work immediately in a new version of Minecraft. 1.13 has by far had the most breaking changes of probably any Minecraft update, as they changed the way blocks' data are handled, and removed integer ID support. However, neither of those things affects a plugin like OCM.

**Comment by I-Al-Istannen** [comment]
We'll have to change the INK_SACK material constant to INK_SAC though.

Then we will have to move away from the `DamageModifier` system some day, as md5 is keen on dropping that for over a year now.

Apart from that I think nothing really needs adjustments, besides maybe updating some dependencies (NBT, the packet listener). Both of these are quite compatible with minecraft changes though, so I don't expect that to need much tinkering.

**Comment by gvlfm78** [comment]
But it could be a problem if we are to keep compatibility with both 1.13+ _and_ 1.9-1.12

**Comment by I-Al-Istannen** [comment]
The INK sack will need to be hidden behind some small abstraction method (unless you have a nicer idea. Maybe some automatic mapping via an internal config file? Sounds a bit more future proof as the names seem to be kinda fluctuating anyways).

I've seen your posts in the thread about the DamageModifier — are you aware of any updates?

If the dependencies e.g. for NBT need an update, that would be a more interesting challenge, yea :/

**Comment by gvlfm78** [comment]
The DamageModifier API just seems to be in a permanent state of `deprecated`, without any real alternative in the Bukkit API. Thus I have simply left it in the code and we should only worry about when it is actually removed, if it ever will be...
