### ISSUE TITLE
ArmorEquipEvent exception

### ISSUE THREAD

**Issue by sgdc3** [gvlfm78/BukkitOldCombatMechanics#229]
## Info

- Server version: Paper 1.13.1
- OldCombatMechanics version: Jenkins build 58
- Server log file: https://hastebin.com/okeculuzaw.cs
- OldCombatMechanics config file: default config

## Problem Description
Exception on armor equip event: https://hastebin.com/okeculuzaw.cs

**Comment by gvlfm78** [comment]
@sgdc3 Those hastebin links don't seem to actually load anything?

**Comment by sgdc3** [comment]
@gvlfm78 that's why i should stop using hastebin, anyway, the cause was that the comphenix Attribute class uses numeric ids for enchants and etc

**Comment by gvlfm78** [comment]
:thinking: and what were they replaced with?

**Comment by sgdc3** [comment]
Minecraft namespaced keys

**Comment by gvlfm78** [comment]
:thinking: :thinking: We'll need to see if there's a way to keep compatibility with both...

**Comment by sgdc3** [comment]
Consider using a nbt library like https://github.com/tr7zw/Item-NBT-API

**Comment by I-Al-Istannen** [comment]
It already uses a (minimal) NBT library. The change does not seem to stem from what you said though @sgdc3.

The reason seems to be that the NBT hierarchy changed from:
```java
public class NBTTagCompound extends NBTBase
```
to
```
public class NBTTagCompound implements NBTBase
```

and the code currently does:
```java
BASE_CLASS = COMPOUND_CLASS.getSuperclass();
```
which now yields `Object` -- which has no getTypeId method.

Do you want to fix that or should I prepare something @gvlfm78?
