### ISSUE TITLE
Sweeping edge enchant doesn't work

### ISSUE THREAD

**Issue by iMaarten** [gvlfm78/BukkitOldCombatMechanics#237]
- Server version: 1.12.2 Paperspigot, build 1552
- OldCombatMechanics version: 1.7.0(Latest dev Build)
- OldCombatMechanics config file:  https://pastebin.com/Kyfn2NAh

## Problem Description
> Sweeping edge enchant stopped working after updating from 1.6.3 to 1.7.0.

**Comment by gvlfm78** [comment]
What do you mean by "Sweeping edge enchant stopped working"?

**Comment by iMaarten** [comment]
As in the enchant does nothing anymore.

**Comment by gvlfm78** [comment]
Well, you have the `disable-sword-sweep` module enabled, so it _shouldn't_ be doing anything...

**Comment by iMaarten** [comment]
Strange, it used to work just fine. Sorry.

**Comment by I-Al-Istannen** [comment]
I mean, Sweeping edge quite literally does this:
![grafik](https://user-images.githubusercontent.com/20284688/45316596-c653a780-b537-11e8-9fb5-f78de8cbacdb.png)

If you *disable sweeping attacks*, what should it do?

**Comment by iMaarten** [comment]
But normally they don't do as much damage, right?

**Comment by I-Al-Istannen** [comment]
Okay, what do you want sweep attacks to do? And how do you want sweeping edge to influence it?

**Comment by gvlfm78** [comment]
I put the warning `IMPORTANT: Also enable disable-sword-sweep module or sweeps will have the damage value of the weapon in hand` because I rewrote the way OCM checks for damage events. I made it _not_ check if the event is a sweep attack and ignore it and thus the sweep damage goes wonky. Consequently, the disable-sword-sweep should be enabled when the other module is enabled. We _can_ add the check into the damage generic listener event, but then most of the computation that occurs within the disable-sword-sweep module would _always_ be going on, during any damage event.
