### ISSUE TITLE
OCM Could not check for updates error: The reference to entity "render" must end with the ';' delimiter.null

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#27]
OCM dev 34

```
[02:22:21] [Craft Scheduler Thread - 7/WARN]: [Fatal Error] :58:86: The reference to entity "render" must end with the ';' delimiter.

[02:22:21] [Craft Scheduler Thread - 7/ERROR]: OCM Could not check for updates error: The reference to entity "render" must end with the ';' delimiter.null

```

**Comment by gvlfm78** [comment]
I don't see this error coming up nowhere. What update check was OCM performing, the startup one? Was there something else to the error message?

**Comment by mibby** [comment]
Nope, that was the entire message. I generate a new config (deleted the folder) and started up the server. Then that output occurred. Maybe it was due to DBO update change if the update checker points there?

**Comment by Rayzr522** [comment]
Curse broke the updater. Sorry for the inconvenience, we'll have to update to use [Gravity's updater](https://bukkit.org/threads/96681/), @gvlfm78.

**Comment by gvlfm78** [comment]
The new graphics are completely all over the place... It's looks as if they forgot what delimiting lines were while designing them...

**Comment by gvlfm78** [comment]
Fun... Our project doesn't seem to appear on the curseforge API... https://api.curseforge.com/servermods/projects?search=oldcombatmechanics

**Comment by gvlfm78** [comment]
Alright they finally made OCM appear on the CurseForge API after I emailed them (not sure if they actually did anything or it automatically fixed itself as I never got a reply). This means the Bukkit update checker now works properly, but I added a version checker so that it only tells you there's an update if there's actually an update and not if you have a development version on.
