### ISSUE TITLE
Could not pass event EntityDamageEvent to OldCombatMechanics

### ISSUE THREAD

**Issue by yanisssch** [gvlfm78/BukkitOldCombatMechanics#312]
- Server version: spigot 1.9.4
- OldCombatMechanics version: 1.7.3
- Server log file: https://pastebin.com/kdfN7P7Z
- OldCombatMechanics config file: https://pastebin.com/4Rdgyajr

## Problem Description
> this error spam my console everytime (ps: don't look fr.yanisssch.PWP.* it's just perworldplugin)

**Comment by gvlfm78** [comment]
Did you have this issue with previous version of OCM too (eg 1.7.2, 1.7.1)?

**Comment by yanisssch** [comment]
i think from 1.7.1 but i'm not sure because i can't test everytime i don't have a lot of player on my server x)

**Comment by Rayzr522** [comment]
Caused due to an oversight with 1.9 compatibility, since 1.9 has no magma blocks and therefore no HOT_BLOCK damage cause (courtesy of the server log from #313, thank you). Fixed in b8697b36fc0cc0de8f998cce8b46f73a711935d1.

Please use [dev build 52](https://ci.rayzr.dev/job/OldCombatMechanics/52/). I tested and the problem was fully resolved on Spigot 1.9.4 for me, so I will close the issue for now. Please re-open the issue if the problem returns.
