### ISSUE TITLE
Chorus Fruit control

### ISSUE THREAD

**Issue by ArtelGG** [gvlfm78/BukkitOldCombatMechanics#321]
- Server version: PaperSpigot 1.14.4-b135
- OldCombatMechanics version: 1.7.4-BETA
- Server log file: N/A
- OldCombatMechanics config file: N/A

> I would like to have control over the Chorus Fruit, specifically in this instance to disable it entirely or perhaps make it just a regular food item, this seems like the most logical plugin to suggest something like this for.

**Comment by gvlfm78** [comment]
Is this because of the teleporting function?

**Comment by ArtelGG** [comment]
Primarily, yes.

**Comment by Rayzr522** [comment]
So basically it looks like we're looking at three potential modes:

1. Normal 1.9+ behavior, nothing changed
2. Completely disabled, you can't eat it at all
3. Use it as a normal food item, with a configurable food/saturation value perhaps, but no teleportation

Right?

**Comment by ArtelGG** [comment]
All of that looks good, the only thing I could even think of that people might want to change it to is a custom teleportation distance, or perhaps controlling where it lands in terms of making it only teleport you onto blocks that weren't placed by a player (to prevent teleporting into peoples bases, that are underground with walls for example).

**Other than that, that looks like a solid set of features.**

**Comment by Rayzr522** [comment]
Hmmm, you raise good points. However, I think that would be the responsibility of a factions plugin, since it's the factions plugin that would be determining what is wilderness, what is enemy territory, etc. Not really the place of our plugin. Definitely might consider adding a configurable distance option for the teleporting tho.

SO it looks like this is what we're thinking of at this point:

1. Normal 1.9+ behavior, nothing changed
2. Completely disabled, you can't eat it at all
3. Use it as a normal food item, with a configurable food/saturation value perhaps, but no teleportation
3. Functions like 1.9+ behavior but with configurable teleportation distance

**Comment by ArtelGG** [comment]
Perhaps you could compact 1. and 4. together and just have a single integer setting that's set to the default distance?

**Comment by Rayzr522** [comment]
Fair enough. We just don't want to mess with the behavior at all really if it's intended to act like vanilla, but I suppose we could just check if the distance is set to the vanilla default.

**Comment by gvlfm78** [comment]
Added in 1.7.4
