### ISSUE TITLE
1.12mc V mod V 1.6.6 not showing up in mods list

### ISSUE THREAD

**Issue by TGIBTheGuyInBlue** [gvlfm78/BukkitOldCombatMechanics#322]
## Info

- Server version: SP Verson 1.12.2 Forge
- OldCombatMechanics version: 1.6.6
- Server log file: 
[latest.log](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/3414645/latest.log)

[2019-07-21-5.log](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/3414646/2019-07-21-5.log)

- OldCombatMechanics config file: does not have one because mod wont load or be seen by forge

## Problem Description
> the mod wont show up idk what else to say plz help

**Comment by gvlfm78** [comment]
OldCombatMechanics is a Bukkit plugin, not a Forge mod.

**Comment by TGIBTheGuyInBlue** [comment]
Ok thx so how do i use a plugin

**Comment by gvlfm78** [comment]
You need to open a server using Bukkit or a derivative (such as Spigot).

**Comment by TGIBTheGuyInBlue** [comment]
So its only for servers darn

**Comment by Rayzr522** [comment]
Yes, although implementing the basic functionality of this in Forge should be relatively simple. It appears there is a mod called [Classic Combat](https://www.curseforge.com/minecraft/mc-mods/classic-combat) which implements a few of the same features as OldCombatMechanics, but as a Forge mod. Perhaps this will be of use to you, although it is not as full-featured as OldCombatMechanics.

**Comment by TGIBTheGuyInBlue** [comment]
Yea i have seen it but what i would like is the ability to block with
swords but i have not seen one yet

**Comment by Rayzr522** [comment]
This isn't really this place for this, but all I will say is you will be hard-pressed to find that because it would require completely overriding the functionality of vanilla swords to re-add the blocking mechanic. Good luck, however! And if you happen to find a mod which provides a more complete re-creation of old combat in newer Minecraft versions, feel free to let us know, so that we can spread the word in case anyone else is looking for a forge-equivalent of OCM.

**Comment by TGIBTheGuyInBlue** [comment]
So just use 1.7 if my pc did not break yesterday well thx for the help
anyway
