### ISSUE TITLE
The residence area will be attacked by fishing rods

### ISSUE THREAD

**Issue by 3154311518** [gvlfm78/BukkitOldCombatMechanics#658]
The residence area will be attacked by fishing rods

https://user-images.githubusercontent.com/46740577/234429590-4b81b4fb-b949-46c8-8d34-c0d97f9375df.mp4

**Comment by kernitus** [comment]
Please follow the issue template. I need a copy of your `config.yml` to know what is going on.

**Comment by kernitus** [comment]
Alright. Can you outline what is happening in the video? I presume you are using the [Residence](https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-19.11480/) plugin.

1. Which of the players belong to the residence and which doesn't? 
2. What do you expect to happen instead of what happens in the video?
