### ISSUE TITLE
addToScoreboard error

### ISSUE THREAD

**Issue by Kizarr** [gvlfm78/BukkitOldCombatMechanics#76]
Version of Bukkit/Spigot:  Spigot 1.11.2 SNAPSHOT Latest Build
Version of OCM plugin: 1.4.2
Copy of my config.yml: https://pastebin.com/BMEYDt2G
Copy of full console error: https://pastebin.com/4aZ9nG3M

**Comment by gvlfm78** [comment]
How often do you get this error, and when?

**Comment by Rayzr522** [comment]
This would be caused by some plugin or player removing the `ocmInternal` team after OCM loads. Do you have any other plugins that deal with the vanilla scoreboards/teams system?

**Comment by BytedByte** [comment]
I'm getting the same error and i'm not quite sure what Vanilla scoreboards/teams are but I do have: Koth, FactionsUUID, LevelHealth, mcMMO. Here's a screenshot of all my plugins if you want to take a look: http://i.imgur.com/TBVjKqZ.png

If you need any additional info or need me to test something i'll be more than glad to do it for u

**Comment by gvlfm78** [comment]
@Kizarr @BytedByte I have just changed the no-collisions module to use packets instead of scoreboards in order to reduce conflicts if not eliminating them entirely.
Please try [test build #135](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/135/) or above and tell me if there still are issues with the module.
